version: '3.8'

services:

  bot:
    container_name: bot
    build:
      context: .
    environment:
      ENV_PATH: envs/stable.envs
      PYTHONUNBUFFERED: 1

  lavalink:
    container_name: lavalink
    image: ghcr.io/lavalink-devs/lavalink:3-alpine
    restart: always
    environment:
      SERVER_PORT: 2333
      LAVALINK_SERVER_PASSWORD: youshallnotpass