version: '3.8'

services:

  bot:
    container_name: bot
    build:
      context: .
    environment:
      ENV_PATH: env/test.env
      PYTHONUNBUFFERED: 1

  lavalink:
    image: fredboat/lavalink:master
    restart: always
    environment:
      LAVA_PORT: 2333
      LAVA_PASSWORD: youshallnotpass
    ports:
      - "2333:2333"
