version: '3.8'

services:

  lavalink:
    container_name: lavalink
    build:
      dockerfile: lavalink/Dockerfile
    volumes:
      - ./lavalink:/usr/src/lavalink

  bot:
    container_name: bot
    build:
      dockerfile: bot/Dockerfile
    environment:
      ENV_PATH: ./env/stable.env
    volumes:
      - ./bot:/usr/src/bot